# Topic Modelling

topic modelling digunakan untuk mengelompokkan data berdasarkan topik tertentu.

Data : komentar dengan kata kunci "capres2024".

Tugas : 
LSA : TF IDF & Singuler Value Decomposition (SVD)

Output: 
- Kontribusi dokumen terhadap topik
- Kontribusi term terhadap topik

In [136]:
import pandas as pd
from googleapiclient.discovery import build

In [137]:
def video_comments(video_id):
	# empty list for storing reply
	replies = []

	# creating youtube resource object
	youtube = build('youtube', 'v3', developerKey=api_key)

	# retrieve youtube video results
	video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

	# iterate video response
	while video_response:
		
		# extracting required info
		# from each result object
		for item in video_response['items']:
			
			# Extracting comments ()
			published = item['snippet']['topLevelComment']['snippet']['publishedAt']
			user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

			# Extracting comments
			comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
			likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

			replies.append([published, user, comment, likeCount])
			
			# counting number of reply of comment
			replycount = item['snippet']['totalReplyCount']

			# if reply is there
			if replycount>0:
				# iterate through all reply
				for reply in item['replies']['comments']:
					
					# Extract reply
					published = reply['snippet']['publishedAt']
					user = reply['snippet']['authorDisplayName']
					repl = reply['snippet']['textDisplay']
					likeCount = reply['snippet']['likeCount']
					
					# Store reply is list
					#replies.append(reply)
					replies.append([published, user, repl, likeCount])

			# print comment with list of reply
			#print(comment, replies, end = '\n\n')

			# empty reply list
			#replies = []

		# Again repeat
		if 'nextPageToken' in video_response:
			video_response = youtube.commentThreads().list(
					part = 'snippet,replies',
					pageToken = video_response['nextPageToken'], 
					videoId = video_id
				).execute()
		else:
			break
	#endwhile
	return replies

In [138]:
api_key = 'AIzaSyD6Lb7fJBcMcxcvKsIRctUXv_bwTyxc56w' 
# url = https://www.youtube.com/watch?v=3NsEq2N7JTY
video_id = "3NsEq2N7JTY" #id video
# Call function
comments = video_comments(video_id)
comments

[['2023-05-09T11:43:10Z',
  'dwi faizal',
  'Prabowo masih tersandra krn koalisinya baru pkb. Kalau deklarasi skrg otomatis cawapresnya si imin yg gak banyak peminatnya. Elektabilitas imin cuma 2 koma. Yang ada elektabilitas prabowo bukannya naik, tapi malah ikutan nyungsep. Ambyarrr...',
  0],
 ['2023-05-09T08:02:07Z',
  'bambang wahyudi',
  'Seandainya terjadi 4 pasangan capres akan lebih semangat...pasangan anis, pasangan prabowo, pasangan gan jar dan pasangan erlangga...rakyat akan senang disungguhkan banyak pilihan ....',
  0],
 ['2023-05-05T12:46:00Z',
  'Son of Luciver',
  'Golput. Siapa pun presidenya tidak ada yang bisa menegakan sila ke 2 keadilab bagi seluruh rakyat indonesia',
  1],
 ['2023-05-04T09:38:07Z',
  'Jamal Abdul Nasir',
  'Prabowo presiden, Ganjar mentri dalam negeri, Anies mentri luar negeri, 😊',
  0],
 ['2023-05-07T14:05:33Z', "zannatul ma'wa", 'Orang baik... semangat', 0],
 ['2023-05-07T14:05:20Z',
  "zannatul ma'wa",
  'Bener ya ayooo dukung....❤️❤️❤️❤️',
  0

In [139]:
df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

publishedAt  authorDisplayName  \
0   2023-05-09T11:43:10Z         dwi faizal   
1   2023-05-09T08:02:07Z    bambang wahyudi   
2   2023-05-05T12:46:00Z     Son of Luciver   
3   2023-05-04T09:38:07Z  Jamal Abdul Nasir   
4   2023-05-07T14:05:33Z     zannatul ma'wa   
5   2023-05-07T14:05:20Z     zannatul ma'wa   
6   2023-05-03T04:08:36Z            EL-FIKR   
7   2023-05-04T20:14:21Z         Evan Haris   
8   2023-05-02T13:49:02Z          Nama kamu   
9   2023-05-07T20:00:09Z       Franaldo Fek   
10  2023-05-01T06:42:20Z         Dafi Fay72   
11  2023-04-30T08:35:24Z        Syamsu Alam   
12  2023-04-29T05:40:16Z      Rohadi Rohadi   
13  2023-05-07T14:02:48Z     zannatul ma'wa   
14  2023-04-29T05:04:38Z       Munkar Nakir   
15  2023-04-29T03:42:21Z     Hafizh Muzakky   
16  2023-04-29T03:10:53Z      Muhson Muhson   
17  2023-04-29T03:43:51Z     Hafizh Muzakky   
18  2023-04-29T03:06:06Z          Yan Phang   
19  2023-04-29T01:39:38Z           Azrar 01   

                                          textDisplay  likeCount  
0   Prabowo masih tersandra krn koalisinya baru pk...          0  
1   Seandainya terjadi 4 pasangan capres akan lebi...          0  
2   Golput. Siapa pun presidenya tidak ada yang bi...          1  
3   Prabowo presiden, Ganjar mentri dalam negeri, ...          0  
4                              Orang baik... semangat          0  
5                   Bener ya ayooo dukung....❤️❤️❤️❤️          0  
6                 Hubungannya kursi sama pilpres apa?          0  
7                         Kursi ya Buat tempat duduk🤣          0  
8              Prabowo Subianto Djojohadikusumo❤ 2024          0  
9                                                 💪💪💪          0  
10  Kenapa golkar dan pan gaa nyalonin presiden. A...          0  
11            Waspada akan munculnya Soehartoisme 🤣🤣🤣          1  
12  Aku seneng dn cinta mbk puan aku bangga pk pra...          2  
13                                       Bener ayoooo          0  
14  ❤*SIAPAPUN PENDUKUNGNYA  (GP) YG PENTING  TIDA...          0  
15  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...          0  
16  P3 nyungsep th 2024  kursi dpr ri  zonk,akar r...          1  
17                   Aamiin yaa Robbal &#39;alamin,,,          0  
18  Munculkan Ridwan Kamil - Erick Tohir sekalian ...          0  
19  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...          0

In [140]:
# df.to_csv("capres2024.csv",index=False)

Preprocessing

1. Cleaninng text
2. Lowercase
3. Slank word
4. Tokenizing
5. Stopword
6. Stemming



In [141]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [142]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [143]:
dt = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/capres2024.csv")
dt

publishedAt  authorDisplayName  \
0   2023-05-09T11:43:10Z         dwi faizal   
1   2023-05-09T08:02:07Z    bambang wahyudi   
2   2023-05-05T12:46:00Z     Son of Luciver   
3   2023-05-04T09:38:07Z  Jamal Abdul Nasir   
4   2023-05-07T14:05:33Z     zannatul ma'wa   
5   2023-05-07T14:05:20Z     zannatul ma'wa   
6   2023-05-03T04:08:36Z            EL-FIKR   
7   2023-05-04T20:14:21Z         Evan Haris   
8   2023-05-02T13:49:02Z          Nama kamu   
9   2023-05-07T20:00:09Z       Franaldo Fek   
10  2023-05-01T06:42:20Z         Dafi Fay72   
11  2023-04-30T08:35:24Z        Syamsu Alam   
12  2023-04-29T05:40:16Z      Rohadi Rohadi   
13  2023-05-07T14:02:48Z     zannatul ma'wa   
14  2023-04-29T05:04:38Z       Munkar Nakir   
15  2023-04-29T03:42:21Z     Hafizh Muzakky   
16  2023-04-29T03:10:53Z      Muhson Muhson   
17  2023-04-29T03:43:51Z     Hafizh Muzakky   
18  2023-04-29T03:06:06Z          Yan Phang   
19  2023-04-29T01:39:38Z           Azrar 01   

                                          textDisplay  likeCount  
0   Prabowo masih tersandra krn koalisinya baru pk...          0  
1   Seandainya terjadi 4 pasangan capres akan lebi...          0  
2   Golput. Siapa pun presidenya tidak ada yang bi...          1  
3   Prabowo presiden, Ganjar mentri dalam negeri, ...          0  
4                              Orang baik... semangat          0  
5                   Bener ya ayooo dukung....❤️❤️❤️❤️          0  
6                 Hubungannya kursi sama pilpres apa?          0  
7                         Kursi ya Buat tempat duduk🤣          0  
8              Prabowo Subianto Djojohadikusumo❤ 2024          0  
9                                                 💪💪💪          0  
10  Kenapa golkar dan pan gaa nyalonin presiden. A...          0  
11            Waspada akan munculnya Soehartoisme 🤣🤣🤣          1  
12  Aku seneng dn cinta mbk puan aku bangga pk pra...          2  
13                                       Bener ayoooo          0  
14  ❤*SIAPAPUN PENDUKUNGNYA  (GP) YG PENTING  TIDA...          0  
15  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...          0  
16  P3 nyungsep th 2024  kursi dpr ri  zonk,akar r...          1  
17                   Aamiin yaa Robbal &#39;alamin,,,          0  
18  Munculkan Ridwan Kamil - Erick Tohir sekalian ...          0  
19  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...          0

In [144]:
#cleaningtext
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', text)
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description setelah dilakukan clean 
preproces= dt['textDisplay'].apply(clean_punct)
dt_clean=pd.DataFrame(preproces)
dt_clean

textDisplay
0   Prabowo masih tersandra krn koalisinya baru pk...
1   Seandainya terjadi   pasangan capres akan lebi...
2   Golput  Siapa pun presidenya tidak ada yang bi...
3   Prabowo presiden  Ganjar mentri dalam negeri  ...
4                              Orang baik    semangat
5                   Bener ya ayooo dukung            
6                 Hubungannya kursi sama pilpres apa 
7                         Kursi ya Buat tempat duduk 
8              Prabowo Subianto Djojohadikusumo      
9                                                    
10  Kenapa golkar dan pan gaa nyalonin presiden  A...
11            Waspada akan munculnya Soehartoisme    
12  Aku seneng dn cinta mbk puan aku bangga pk pra...
13                                       Bener ayoooo
14    SIAPAPUN PENDUKUNGNYA   GP  YG PENTING  TIDA...
15  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...
16  P  nyungsep th       kursi dpr ri  zonk akar r...
17                               Aamiin yaa Robbal   
18  Munculkan Ridwan Kamil   Erick Tohir sekalian ...
19  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...

In [145]:
#lowercase
def clean_lower(lwr):
    lwr = lwr.lower() # lowercase text
    return lwr
# Buat kolom tambahan untuk data description yang telah dicasefolding  
dt_clean = dt_clean['textDisplay'].apply(clean_lower)
dt_lowecase=pd.DataFrame(dt_clean)
dt_lowecase

textDisplay
0   prabowo masih tersandra krn koalisinya baru pk...
1   seandainya terjadi   pasangan capres akan lebi...
2   golput  siapa pun presidenya tidak ada yang bi...
3   prabowo presiden  ganjar mentri dalam negeri  ...
4                              orang baik    semangat
5                   bener ya ayooo dukung            
6                 hubungannya kursi sama pilpres apa 
7                         kursi ya buat tempat duduk 
8              prabowo subianto djojohadikusumo      
9                                                    
10  kenapa golkar dan pan gaa nyalonin presiden  a...
11            waspada akan munculnya soehartoisme    
12  aku seneng dn cinta mbk puan aku bangga pk pra...
13                                       bener ayoooo
14    siapapun pendukungnya   gp  yg penting  tida...
15  iwan pahlawan noor mb ketapang sampit hadir n ...
16  p  nyungsep th       kursi dpr ri  zonk akar r...
17                               aamiin yaa robbal   
18  munculkan ridwan kamil   erick tohir sekalian ...
19  gerindra dan pkb seharusnya sudah gas pool cap...

#slankword

In [146]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [147]:
!pip install indoNLP

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [148]:
slang_dict = pd.read_csv("https://raw.githubusercontent.com/zakkiya/prosaindata/main/slankwordcapres.txt", sep=" ", header=None)
from indoNLP.preprocessing import replace_slang
from indoNLP.preprocessing import replace_word_elongation
replace_slang
def replace_slang_words(text):
    words = nltk.word_tokenize(text.lower())
    words_filtered = [word for word in words if word not in stopwords.words('indonesian')]
    for i in range(len(words_filtered)):
        if words_filtered[i] in slang_dict:
            words_filtered[i] = slang_dict[words_filtered[i]]
    return ' '.join(words_filtered)

# penggunaan
dt_lowecase=[]
for i in range(len(dt_clean)):
  dt_lowecase.append(dt_clean[i])

slang_words=[]
for i in range(len(dt_lowecase)):
  slang = replace_slang_words(dt_lowecase[i])
  y=replace_slang(slang)
  slang_words.append(y)

slang = pd.DataFrame(slang_words, columns=["data"])
slang

data
0   prabowo tersandra karena koalisinya pkb deklar...
1   seandainya pasangan capres semangat pasangan a...
2   golput presidenya menegakan sila keadilab raky...
3   prabowo presiden ganjar mentri negeri anies me...
4                                      orang semangat
5                                 benar ya ayo dukung
6                           hubungannya kursi pilpres
7                                      kursi ya duduk
8                    prabowo subianto djojohadikusumo
9                                                    
10  golkar kapan enggak nyalonin presiden takut ka...
11                     waspada munculnya soehartoisme
12  senang dan cinta mbak puan bangga pakai prabow...
13                                          benar ayo
14  pendukungnya gp yang berafiliasi dengan kaum b...
15  iwan pahlawan noor mbak ketapang sampit hadir ...
16  p nyungsep tahu kursi dpr ri zonk akar rumput ...
17                                     amin ya robbal
18     munculkan ridwan kamil erick tohir biar partai
19  gerindra pkb gas pool capres n cawapres yang g...

In [149]:
tokenize=[]
for i in range(len(slang_words)):
  token=word_tokenize(slang_words[i])
  tokendata = []
  for x in token :
    tokendata.append(x)
  tokenize.append(tokendata)
  print(tokendata)

['prabowo', 'tersandra', 'karena', 'koalisinya', 'pkb', 'deklarasi', 'sekarang', 'otomatis', 'cawapresnya', 'sih', 'imin', 'yang', 'enggak', 'peminatnya', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikutan', 'nyungsep', 'ambyarrr']
['seandainya', 'pasangan', 'capres', 'semangat', 'pasangan', 'anis', 'pasangan', 'prabowo', 'pasangan', 'gan', 'jar', 'pasangan', 'erlangga', 'rakyat', 'senang', 'disungguhkan', 'pilihan']
['golput', 'presidenya', 'menegakan', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'mentri', 'negeri', 'anies', 'mentri', 'negeri']
['orang', 'semangat']
['benar', 'ya', 'ayo', 'dukung']
['hubungannya', 'kursi', 'pilpres']
['kursi', 'ya', 'duduk']
['prabowo', 'subianto', 'djojohadikusumo']
[]
['golkar', 'kapan', 'enggak', 'nyalonin', 'presiden', 'takut', 'kalah', 'cari', 'aman', 'partai', 'santai']
['waspada', 'munculnya', 'soehartoisme']
['senang', 'dan', 'cinta', 'mbak', 'puan', 'bangga', 'pakai', 'prabowo', 'presiden', '

In [150]:
stopword=[]
for i in range(len(tokenize)):
  listStopword =  set(stopwords.words('indonesian'))
  removed=[]
  for x in (tokenize[i]):
    if x not in listStopword:
       removed.append(x)
  stopword.append(removed)
  print(removed)

['prabowo', 'tersandra', 'koalisinya', 'pkb', 'deklarasi', 'otomatis', 'cawapresnya', 'sih', 'imin', 'peminatnya', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikutan', 'nyungsep', 'ambyarrr']
['seandainya', 'pasangan', 'capres', 'semangat', 'pasangan', 'anis', 'pasangan', 'prabowo', 'pasangan', 'gan', 'jar', 'pasangan', 'erlangga', 'rakyat', 'senang', 'disungguhkan', 'pilihan']
['golput', 'presidenya', 'menegakan', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'mentri', 'negeri', 'anies', 'mentri', 'negeri']
['orang', 'semangat']
['ya', 'ayo', 'dukung']
['hubungannya', 'kursi', 'pilpres']
['kursi', 'ya', 'duduk']
['prabowo', 'subianto', 'djojohadikusumo']
[]
['golkar', 'nyalonin', 'presiden', 'takut', 'kalah', 'cari', 'aman', 'partai', 'santai']
['waspada', 'munculnya', 'soehartoisme']
['senang', 'cinta', 'mbak', 'puan', 'bangga', 'pakai', 'prabowo', 'presiden', 'bismillah', 'pilih', 'pakai', 'anis', 'allohuakbar']
['ayo']
['pendukungnya

In [151]:
stemming=[]
for i in range(len(stopword)):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  katastem=[]
  for x in (stopword[i]):
    katastem.append(stemmer.stem(x))
  stemming.append(katastem)
  print(katastem)

['prabowo', 'tersandra', 'koalisi', 'pkb', 'deklarasi', 'otomatis', 'cawapresnya', 'sih', 'imin', 'minat', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikut', 'nyungsep', 'ambyarrr']
['anda', 'pasang', 'capres', 'semangat', 'pasang', 'anis', 'pasang', 'prabowo', 'pasang', 'gan', 'jar', 'pasang', 'erlangga', 'rakyat', 'senang', 'sungguh', 'pilih']
['golput', 'presidenya', 'tega', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'tri', 'negeri', 'anies', 'tri', 'negeri']
['orang', 'semangat']
['ya', 'ayo', 'dukung']
['hubung', 'kursi', 'pilpres']
['kursi', 'ya', 'duduk']
['prabowo', 'subianto', 'djojohadikusumo']
[]
['golkar', 'nyalonin', 'presiden', 'takut', 'kalah', 'cari', 'aman', 'partai', 'santai']
['waspada', 'muncul', 'soehartoisme']
['senang', 'cinta', 'mbak', 'puan', 'bangga', 'pakai', 'prabowo', 'presiden', 'bismillah', 'pilih', 'pakai', 'anis', 'allohuakbar']
['ayo']
['dukung', 'gp', 'afiliasi', 'kaum', 'biadab', 'tengger', 'jargon'

In [152]:
join=[]
for i in range(len(stemming)):
  joinkata = ' '.join(stemming[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['data'])
hasilpreproses

data
0   prabowo tersandra koalisi pkb deklarasi otomat...
1   anda pasang capres semangat pasang anis pasang...
2   golput presidenya tega sila keadilab rakyat in...
3   prabowo presiden ganjar tri negeri anies tri n...
4                                      orang semangat
5                                       ya ayo dukung
6                                hubung kursi pilpres
7                                      kursi ya duduk
8                    prabowo subianto djojohadikusumo
9                                                    
10  golkar nyalonin presiden takut kalah cari aman...
11                        waspada muncul soehartoisme
12  senang cinta mbak puan bangga pakai prabowo pr...
13                                                ayo
14  dukung gp afiliasi kaum biadab tengger jargon ...
15  iwan pahlawan noor mbak ketapang sampit hadir ...
16  p nyungsep kursi dpr ri zonk akar rumput pilih...
17                                     amin ya robbal
18        muncul ridwan kamil erick tohir biar partai
19  gerindra pkb gas pool capres n cawapres gabung...

TF IDF

In [153]:
tr_model  = TfidfVectorizer()
tf_vector = tr_model.fit_transform(hasilpreproses['data'])

In [154]:
tf_array = tf_vector.toarray()
print(tf_array)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.50461804 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [155]:
words_set = tr_model.get_feature_names_out()
print(words_set)

['afiliasi' 'agama' 'akan' 'akar' 'akibat' 'aksi' 'alat' 'allohuakbar'
 'aman' 'ambisi' 'ambyarrr' 'amin' 'anda' 'aneh' 'anies' 'anis' 'apa'
 'arb' 'ayat' 'ayo' 'badan' 'baik' 'baju' 'balut' 'bangga' 'bangsa'
 'baswedan' 'biadab' 'biar' 'bismillah' 'buai' 'bukti' 'busuk' 'capres'
 'cari' 'cawapres' 'cawapresnya' 'cinta' 'comot' 'dailih' 'dalih' 'dalil'
 'dampak' 'dandan' 'dekat' 'deklarasi' 'delusi' 'demokrasi' 'derajat'
 'didholimi' 'didik' 'djojohadikusumo' 'dki' 'dll' 'dosa' 'dpr' 'duduk'
 'dukung' 'dungu' 'durjana' 'egois' 'elektabilitas' 'erick' 'erlangga'
 'faham' 'fakta' 'fatamorgana' 'gabung' 'gan' 'ganggu' 'ganjar' 'gas'
 'gerindra' 'golkar' 'golput' 'gp' 'hadir' 'halal' 'halusinasi' 'hasil'
 'hubung' 'iblis' 'identitas' 'idiologi' 'ikut' 'imajinasi' 'iman' 'imin'
 'indonesia' 'iwan' 'jadi' 'jamin' 'jar' 'jargon' 'juang' 'kader' 'kalah'
 'kamil' 'kaum' 'keadilab' 'keagamisan' 'keburu' 'kejumawaan' 'kes'
 'ketapang' 'keummatan' 'koalisi' 'koma' 'koyak' 'kuasa' 'kursi' 'kutu'
 '

In [156]:
df = pd.DataFrame(tf_array, columns = words_set)
df

afiliasi     agama      akan      akar    akibat     aksi     alat  \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
12  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
14  0.042985  0.171941  0.042985  0.000000  0.042985  0.08597  0.08597   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
16  0.000000  0.000000  0.000000  0.373341  0.000000  0.00000  0.00000   
17  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  0.00000   

    allohuakbar      aman   ambisi  ...     tuhan     tutup      ubah  \
0      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
1      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
2      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
3      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
4      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
5      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
6      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
7      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
8      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
9      0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
10     0.000000  0.355116  0.00000  ...  0.000000  0.000000  0.000000   
11     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
12     0.276602  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
13     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
14     0.000000  0.000000  0.08597  ...  0.042985  0.042985  0.042985   
15     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
16     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
17     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
18     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   
19     0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000   

        ulah      usak     usung     waras   waspada        ya      zonk  
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.537327  0.000000  
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.494720  0.000000  
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
11  0.000000  0

Singular Value Decomposition


teknik untuk mendekomposisi matriks berukuran apa saja (biasanya diaplikasikan untuk matriks dengan ukuran sangat besar), untuk mempermudah pengolahan data

In [157]:
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=3, algorithm='randomized', n_iter=10, random_state=42)
lsa_top=lsa_model.fit_transform(df)

In [158]:
print(lsa_top)
print(lsa_top.shape)  # (no_of_doc*no_of_topics)

[[ 0.03061356 -0.16592111  0.32844741]
 [ 0.01932149 -0.12515166  0.37850078]
 [ 0.00108228 -0.01238534  0.05646301]
 [ 0.07464898 -0.23103491  0.41642131]
 [ 0.0020667  -0.03300901  0.1160418 ]
 [ 0.82415775  0.41948782  0.04871806]
 [ 0.16274839 -0.36185288 -0.40110016]
 [ 0.50731104 -0.36769531 -0.37005398]
 [ 0.01761732 -0.15746771  0.40684492]
 [ 0.          0.          0.        ]
 [ 0.03885184 -0.11547973  0.20861209]
 [ 0.0008689  -0.01271043  0.04858116]
 [ 0.07074792 -0.23497064  0.48746005]
 [ 0.55656222  0.65511661  0.09615253]
 [ 0.02546976 -0.00848132  0.08989087]
 [ 0.53227341 -0.35903715  0.17237855]
 [ 0.15602447 -0.36353412 -0.2481975 ]
 [ 0.58930039 -0.29763204 -0.02878469]
 [ 0.004221   -0.03186055  0.08851829]
 [ 0.14304435  0.05160695  0.15422297]]
(20, 3)


In [159]:
#bobot setiap topik terhadap dokumen
dt = pd.DataFrame(lsa_top, columns=['topik1','topik2','topik3'])
dt

topik1    topik2    topik3
0   0.030614 -0.165921  0.328447
1   0.019321 -0.125152  0.378501
2   0.001082 -0.012385  0.056463
3   0.074649 -0.231035  0.416421
4   0.002067 -0.033009  0.116042
5   0.824158  0.419488  0.048718
6   0.162748 -0.361853 -0.401100
7   0.507311 -0.367695 -0.370054
8   0.017617 -0.157468  0.406845
9   0.000000  0.000000  0.000000
10  0.038852 -0.115480  0.208612
11  0.000869 -0.012710  0.048581
12  0.070748 -0.234971  0.487460
13  0.556562  0.655117  0.096153
14  0.025470 -0.008481  0.089891
15  0.532273 -0.359037  0.172379
16  0.156024 -0.363534 -0.248197
17  0.589300 -0.297632 -0.028785
18  0.004221 -0.031861  0.088518
19  0.143044  0.051607  0.154223

In [160]:
V = lsa_model.components_
print(V)
print(V.shape) # (no_of_topics*no_of_words)

[[ 5.57021793e-04  2.22808717e-03  5.57021793e-04  2.96888419e-02
   5.57021793e-04  1.11404359e-03  1.11404359e-03  9.98101418e-03
   7.03212907e-03  1.11404359e-03  3.38141898e-03  2.50852640e-01
   1.66086070e-03  1.11404359e-03  7.77863866e-02  1.02333862e-02
   5.57021793e-04  5.57021793e-04  5.57021793e-04  5.56562219e-01
   5.57021793e-04  5.57021793e-04  5.57021793e-04  1.11404359e-03
   9.98101418e-03  3.34213076e-03  7.68752998e-02  2.78510896e-03
   8.32736659e-04  9.98101418e-03  5.57021793e-04  5.57021793e-04
   5.57021793e-04  2.19992893e-02  7.03212907e-03  2.44037955e-02
   3.38141898e-03  9.98101418e-03  1.11404359e-03  5.57021793e-04
   1.11404359e-03  1.67106538e-03  5.57021793e-04  5.57021793e-04
   5.57021793e-04  3.38141898e-03  1.67106538e-03  1.11404359e-03
   5.57021793e-04  5.57021793e-04  5.57021793e-04  5.71841983e-03
   5.57021793e-04  5.57021793e-04  5.57021793e-04  2.96888419e-02
   1.75986790e-01  2.99631340e-01  5.57021793e-04  1.11404359e-03
   5.57021

In [161]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,219):
  masukan = f"kata ke-{i}"
  label.append(masukan)
tabel = pd.DataFrame(V,columns=label)
tabel.rename(index={0:"topik1",1:"topik2",2:"topik3"})

kata ke-1  kata ke-2  kata ke-3  kata ke-4  kata ke-5  kata ke-6  \
topik1   0.000557   0.002228   0.000557   0.029689   0.000557   0.001114   
topik2  -0.000249  -0.000995  -0.000249  -0.095921  -0.000249  -0.000498   
topik3   0.002891   0.011566   0.002891  -0.069503   0.002891   0.005783   

        kata ke-7  kata ke-8  kata ke-9  kata ke-10  ...  kata ke-209  \
topik1   0.001114   0.009981   0.007032    0.001114  ...     0.000557   
topik2  -0.000498  -0.045493  -0.029051   -0.000498  ...    -0.000249   
topik3   0.005783   0.101082   0.055693    0.005783  ...     0.002891   

        kata ke-210  kata ke-211  kata ke-212  kata ke-213  kata ke-214  \
topik1     0.000557     0.000557     0.000557     0.000557     0.000557   
topik2    -0.000249    -0.000249    -0.000249    -0.000249    -0.000249   
topik3     0.002891     0.002891     0.002891     0.002891     0.002891   

        kata ke-215  kata ke-216  kata ke-217  kata ke-218  
topik1     0.001671     0.000290     0.560863     0.029689  
topik2    -0.000747    -0.005105    -0.127247    -0.095921  
topik3     0.008674     0.021844    -0.102483    -0.069503  

[3 rows x 218 columns]