# Topic Modelling

topic modelling digunakan untuk mengelompokkan data berdasarkan topik tertentu.

Data : komentar dengan kata kunci "capres2024".

Tugas : 
LSA : TF IDF & Singuler Value Decomposition (SVD)

Output: 
- Kontribusi dokumen terhadap topik
- Kontribusi term terhadap topik

In [176]:
!pwd

/content/drive/MyDrive/prosaindata/tugas


In [177]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [178]:
%cd /content/drive/MyDrive

/content/drive/MyDrive


In [179]:
!mkdir prosaindata

mkdir: cannot create directory ‘prosaindata’: File exists


In [180]:
%cd prosaindata

/content/drive/MyDrive/prosaindata


In [181]:
!mkdir tugas

mkdir: cannot create directory ‘tugas’: File exists


In [182]:
%cd tugas

/content/drive/MyDrive/prosaindata/tugas


In [183]:
import pandas as pd
from googleapiclient.discovery import build

In [184]:
def video_comments(video_id):
	# empty list for storing reply
	replies = []

	# creating youtube resource object
	youtube = build('youtube', 'v3', developerKey=api_key)

	# retrieve youtube video results
	video_response = youtube.commentThreads().list(part='snippet,replies', videoId=video_id).execute()

	# iterate video response
	while video_response:
		
		# extracting required info
		# from each result object
		for item in video_response['items']:
			
			# Extracting comments ()
			published = item['snippet']['topLevelComment']['snippet']['publishedAt']
			user = item['snippet']['topLevelComment']['snippet']['authorDisplayName']

			# Extracting comments
			comment = item['snippet']['topLevelComment']['snippet']['textDisplay']
			likeCount = item['snippet']['topLevelComment']['snippet']['likeCount']

			replies.append([published, user, comment, likeCount])
			
			# counting number of reply of comment
			replycount = item['snippet']['totalReplyCount']

			# if reply is there
			if replycount>0:
				# iterate through all reply
				for reply in item['replies']['comments']:
					
					# Extract reply
					published = reply['snippet']['publishedAt']
					user = reply['snippet']['authorDisplayName']
					repl = reply['snippet']['textDisplay']
					likeCount = reply['snippet']['likeCount']
					
					# Store reply is list
					#replies.append(reply)
					replies.append([published, user, repl, likeCount])

			# print comment with list of reply
			#print(comment, replies, end = '\n\n')

			# empty reply list
			#replies = []

		# Again repeat
		if 'nextPageToken' in video_response:
			video_response = youtube.commentThreads().list(
					part = 'snippet,replies',
					pageToken = video_response['nextPageToken'], 
					videoId = video_id
				).execute()
		else:
			break
	#endwhile
	return replies

In [185]:
api_key = 'AIzaSyD6Lb7fJBcMcxcvKsIRctUXv_bwTyxc56w' 
# url = https://www.youtube.com/watch?v=3NsEq2N7JTY
video_id = "3NsEq2N7JTY" #id video
# Call function
comments = video_comments(video_id)
comments

[['2023-05-11T00:52:55Z',
  'Husin Syawali',
  'Pak Prabowo presiden, mudah²han urusan papua langsung selesai.',
  0],
 ['2023-05-11T00:16:54Z', 'Tubi Kastubi', 'Anies Baswedan is the best', 0],
 ['2023-05-10T17:43:52Z',
  'Herry Boenawan',
  '❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDEN RI 2024 KITA PASTI MENANG',
  0],
 ['2023-05-10T17:43:05Z',
  'Herry Boenawan',
  '❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDEN RI 2024 SIAP KITA DUKUNG &amp; PASTI MENANG ..',
  0],
 ['2023-05-09T11:43:10Z',
  'dwi faizal',
  'Prabowo masih tersandra krn koalisinya baru pkb. Kalau deklarasi skrg otomatis cawapresnya si imin yg gak banyak peminatnya. Elektabilitas imin cuma 2 koma. Yang ada elektabilitas prabowo bukannya naik, tapi malah ikutan nyungsep. Ambyarrr...',
  0],
 ['2023-05-09T08:02:07Z',
  'bambang wahyudi',
  'Seandainya terjadi 4 pasangan capres akan lebih semangat...pasangan anis, pasangan prabowo, pasangan gan jar dan pasangan erlangga...rakyat akan senang disungguhkan banyak pili

In [186]:
df = pd.DataFrame(comments, columns=['publishedAt', 'authorDisplayName', 'textDisplay', 'likeCount'])
df

publishedAt  authorDisplayName  \
0   2023-05-11T00:52:55Z      Husin Syawali   
1   2023-05-11T00:16:54Z       Tubi Kastubi   
2   2023-05-10T17:43:52Z     Herry Boenawan   
3   2023-05-10T17:43:05Z     Herry Boenawan   
4   2023-05-09T11:43:10Z         dwi faizal   
5   2023-05-09T08:02:07Z    bambang wahyudi   
6   2023-05-05T12:46:00Z     Son of Luciver   
7   2023-05-04T09:38:07Z  Jamal Abdul Nasir   
8   2023-05-07T14:05:33Z     zannatul ma'wa   
9   2023-05-07T14:05:20Z     zannatul ma'wa   
10  2023-05-03T04:08:36Z            EL-FIKR   
11  2023-05-04T20:14:21Z         Evan Haris   
12  2023-05-02T13:49:02Z          Nama kamu   
13  2023-05-07T20:00:09Z       Franaldo Fek   
14  2023-05-01T06:42:20Z         Dafi Fay72   
15  2023-04-30T08:35:24Z        Syamsu Alam   
16  2023-04-29T05:40:16Z      Rohadi Rohadi   
17  2023-05-07T14:02:48Z     zannatul ma'wa   
18  2023-04-29T05:04:38Z       Munkar Nakir   
19  2023-04-29T03:42:21Z     Hafizh Muzakky   
20  2023-04-29T03:10:53Z      Muhson Muhson   
21  2023-04-29T03:43:51Z     Hafizh Muzakky   
22  2023-04-29T03:06:06Z          Yan Phang   
23  2023-04-29T01:39:38Z           Azrar 01   

                                          textDisplay  likeCount  
0   Pak Prabowo presiden, mudah²han urusan papua l...          0  
1                          Anies Baswedan is the best          0  
2   ❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDE...          0  
3   ❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDE...          0  
4   Prabowo masih tersandra krn koalisinya baru pk...          0  
5   Seandainya terjadi 4 pasangan capres akan lebi...          0  
6   Golput. Siapa pun presidenya tidak ada yang bi...          1  
7   Prabowo presiden, Ganjar mentri dalam negeri, ...          0  
8                              Orang baik... semangat          0  
9                   Bener ya ayooo dukung....❤️❤️❤️❤️          0  
10                Hubungannya kursi sama pilpres apa?          0  
11                        Kursi ya Buat tempat duduk🤣          0  
12             Prabowo Subianto Djojohadikusumo❤ 2024          1  
13                                                💪💪💪          0  
14  Kenapa golkar dan pan gaa nyalonin presiden. A...          0  
15            Waspada akan munculnya Soehartoisme 🤣🤣🤣          1  
16  Aku seneng dn cinta mbk puan aku bangga pk pra...          2  
17                                       Bener ayoooo          0  
18  ❤*SIAPAPUN PENDUKUNGNYA  (GP) YG PENTING  TIDA...          0  
19  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...          0  
20  P3 nyungsep th 2024  kursi dpr ri  zonk,akar r...          1  
21                   Aamiin yaa Robbal &#39;alamin,,,          0  
22  Munculkan Ridwan Kamil - Erick Tohir sekalian ...          0  
23  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...          0

In [187]:
df.to_csv("capres2024.csv",index=False)

Preprocessing

1. Cleaninng text
2. Lowercase
3. Slank word
4. Tokenizing
5. Stopword
6. Stemming



In [188]:
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [189]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
import re
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from nltk.tokenize import sent_tokenize, word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [190]:
dt = pd.read_csv("/content/drive/MyDrive/prosaindata/tugas/capres2024.csv")
dt

publishedAt  authorDisplayName  \
0   2023-05-11T00:52:55Z      Husin Syawali   
1   2023-05-11T00:16:54Z       Tubi Kastubi   
2   2023-05-10T17:43:52Z     Herry Boenawan   
3   2023-05-10T17:43:05Z     Herry Boenawan   
4   2023-05-09T11:43:10Z         dwi faizal   
5   2023-05-09T08:02:07Z    bambang wahyudi   
6   2023-05-05T12:46:00Z     Son of Luciver   
7   2023-05-04T09:38:07Z  Jamal Abdul Nasir   
8   2023-05-07T14:05:33Z     zannatul ma'wa   
9   2023-05-07T14:05:20Z     zannatul ma'wa   
10  2023-05-03T04:08:36Z            EL-FIKR   
11  2023-05-04T20:14:21Z         Evan Haris   
12  2023-05-02T13:49:02Z          Nama kamu   
13  2023-05-07T20:00:09Z       Franaldo Fek   
14  2023-05-01T06:42:20Z         Dafi Fay72   
15  2023-04-30T08:35:24Z        Syamsu Alam   
16  2023-04-29T05:40:16Z      Rohadi Rohadi   
17  2023-05-07T14:02:48Z     zannatul ma'wa   
18  2023-04-29T05:04:38Z       Munkar Nakir   
19  2023-04-29T03:42:21Z     Hafizh Muzakky   
20  2023-04-29T03:10:53Z      Muhson Muhson   
21  2023-04-29T03:43:51Z     Hafizh Muzakky   
22  2023-04-29T03:06:06Z          Yan Phang   
23  2023-04-29T01:39:38Z           Azrar 01   

                                          textDisplay  likeCount  
0   Pak Prabowo presiden, mudah²han urusan papua l...          0  
1                          Anies Baswedan is the best          0  
2   ❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDE...          0  
3   ❤️❤️❤️ THE BEST OF THE BEST - PRABOWO  PRESIDE...          0  
4   Prabowo masih tersandra krn koalisinya baru pk...          0  
5   Seandainya terjadi 4 pasangan capres akan lebi...          0  
6   Golput. Siapa pun presidenya tidak ada yang bi...          1  
7   Prabowo presiden, Ganjar mentri dalam negeri, ...          0  
8                              Orang baik... semangat          0  
9                   Bener ya ayooo dukung....❤️❤️❤️❤️          0  
10                Hubungannya kursi sama pilpres apa?          0  
11                        Kursi ya Buat tempat duduk🤣          0  
12             Prabowo Subianto Djojohadikusumo❤ 2024          1  
13                                                💪💪💪          0  
14  Kenapa golkar dan pan gaa nyalonin presiden. A...          0  
15            Waspada akan munculnya Soehartoisme 🤣🤣🤣          1  
16  Aku seneng dn cinta mbk puan aku bangga pk pra...          2  
17                                       Bener ayoooo          0  
18  ❤*SIAPAPUN PENDUKUNGNYA  (GP) YG PENTING  TIDA...          0  
19  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...          0  
20  P3 nyungsep th 2024  kursi dpr ri  zonk,akar r...          1  
21                   Aamiin yaa Robbal &#39;alamin,,,          0  
22  Munculkan Ridwan Kamil - Erick Tohir sekalian ...          0  
23  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...          0

In [191]:
#cleaningtext
clean_tag = re.compile('@\S+')
clean_url = re.compile('https?:\/\/.*[\r\n]*')
clean_hastag = re.compile('#\S+')
clean_symbol = re.compile('[^a-zA-Z]')
def clean_punct(text):
    text = clean_tag.sub('', text)
    text = clean_url.sub('', text)
    text = clean_hastag.sub(' ', text)
    text = clean_symbol.sub(' ', text)
    return text
# Buat kolom tambahan untuk data description setelah dilakukan clean 
preproces= dt['textDisplay'].apply(clean_punct)
dt_clean=pd.DataFrame(preproces)
dt_clean

textDisplay
0   Pak Prabowo presiden  mudah han urusan papua l...
1                          Anies Baswedan is the best
2          THE BEST OF THE BEST   PRABOWO  PRESIDE...
3          THE BEST OF THE BEST   PRABOWO  PRESIDE...
4   Prabowo masih tersandra krn koalisinya baru pk...
5   Seandainya terjadi   pasangan capres akan lebi...
6   Golput  Siapa pun presidenya tidak ada yang bi...
7   Prabowo presiden  Ganjar mentri dalam negeri  ...
8                              Orang baik    semangat
9                   Bener ya ayooo dukung            
10                Hubungannya kursi sama pilpres apa 
11                        Kursi ya Buat tempat duduk 
12             Prabowo Subianto Djojohadikusumo      
13                                                   
14  Kenapa golkar dan pan gaa nyalonin presiden  A...
15            Waspada akan munculnya Soehartoisme    
16  Aku seneng dn cinta mbk puan aku bangga pk pra...
17                                       Bener ayoooo
18    SIAPAPUN PENDUKUNGNYA   GP  YG PENTING  TIDA...
19  Iwan Pahlawan Noor MB Ketapang Sampit Hadir N ...
20  P  nyungsep th       kursi dpr ri  zonk akar r...
21                               Aamiin yaa Robbal   
22  Munculkan Ridwan Kamil   Erick Tohir sekalian ...
23  Gerindra dan PKB SEHARUSNYA SUDAH GAS POOL CAP...

In [192]:
#lowercase
def clean_lower(lwr):
    lwr = lwr.lower() # lowercase text
    return lwr
# Buat kolom tambahan untuk data description yang telah dicasefolding  
dt_clean = dt_clean['textDisplay'].apply(clean_lower)
dt_lowecase=pd.DataFrame(dt_clean)
dt_lowecase

textDisplay
0   pak prabowo presiden  mudah han urusan papua l...
1                          anies baswedan is the best
2          the best of the best   prabowo  preside...
3          the best of the best   prabowo  preside...
4   prabowo masih tersandra krn koalisinya baru pk...
5   seandainya terjadi   pasangan capres akan lebi...
6   golput  siapa pun presidenya tidak ada yang bi...
7   prabowo presiden  ganjar mentri dalam negeri  ...
8                              orang baik    semangat
9                   bener ya ayooo dukung            
10                hubungannya kursi sama pilpres apa 
11                        kursi ya buat tempat duduk 
12             prabowo subianto djojohadikusumo      
13                                                   
14  kenapa golkar dan pan gaa nyalonin presiden  a...
15            waspada akan munculnya soehartoisme    
16  aku seneng dn cinta mbk puan aku bangga pk pra...
17                                       bener ayoooo
18    siapapun pendukungnya   gp  yg penting  tida...
19  iwan pahlawan noor mb ketapang sampit hadir n ...
20  p  nyungsep th       kursi dpr ri  zonk akar r...
21                               aamiin yaa robbal   
22  munculkan ridwan kamil   erick tohir sekalian ...
23  gerindra dan pkb seharusnya sudah gas pool cap...

#slankword

In [193]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [194]:
!pip install indoNLP

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [195]:
slang_dict = pd.read_csv("https://raw.githubusercontent.com/zakkiya/prosaindata/main/slankwordcapres.txt", sep=" ", header=None)
from indoNLP.preprocessing import replace_slang
from indoNLP.preprocessing import replace_word_elongation
replace_slang
def replace_slang_words(text):
    words = nltk.word_tokenize(text.lower())
    words_filtered = [word for word in words if word not in stopwords.words('indonesian')]
    for i in range(len(words_filtered)):
        if words_filtered[i] in slang_dict:
            words_filtered[i] = slang_dict[words_filtered[i]]
    return ' '.join(words_filtered)

# penggunaan
dt_lowecase=[]
for i in range(len(dt_clean)):
  dt_lowecase.append(dt_clean[i])

slang_words=[]
for i in range(len(dt_lowecase)):
  slang = replace_slang_words(dt_lowecase[i])
  y=replace_slang(slang)
  slang_words.append(y)

slang = pd.DataFrame(slang_words, columns=["data"])
slang

data
0   prabowo presiden mudah han urusan papua langsu...
1                          anies baswedan is the best
2     the best of the best prabowo presiden ri menang
3   the best of the best prabowo presiden ri dukun...
4   prabowo tersandra karena koalisinya pkb deklar...
5   seandainya pasangan capres semangat pasangan a...
6   golput presidenya menegakan sila keadilab raky...
7   prabowo presiden ganjar mentri negeri anies me...
8                                      orang semangat
9                                 benar ya ayo dukung
10                          hubungannya kursi pilpres
11                                     kursi ya duduk
12                   prabowo subianto djojohadikusumo
13                                                   
14  golkar kapan enggak nyalonin presiden takut ka...
15                     waspada munculnya soehartoisme
16  senang dan cinta mbak puan bangga pakai prabow...
17                                          benar ayo
18  pendukungnya gp yang berafiliasi dengan kaum b...
19  iwan pahlawan noor mbak ketapang sampit hadir ...
20  p nyungsep tahu kursi dpr ri zonk akar rumput ...
21                                     amin ya robbal
22     munculkan ridwan kamil erick tohir biar partai
23  gerindra pkb gas pool capres n cawapres yang g...

In [196]:
tokenize=[]
for i in range(len(slang_words)):
  token=word_tokenize(slang_words[i])
  tokendata = []
  for x in token :
    tokendata.append(x)
  tokenize.append(tokendata)
  print(tokendata)

['prabowo', 'presiden', 'mudah', 'han', 'urusan', 'papua', 'langsung', 'selesai']
['anies', 'baswedan', 'is', 'the', 'best']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'menang']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'dukung', 'amp', 'menang']
['prabowo', 'tersandra', 'karena', 'koalisinya', 'pkb', 'deklarasi', 'sekarang', 'otomatis', 'cawapresnya', 'sih', 'imin', 'yang', 'enggak', 'peminatnya', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikutan', 'nyungsep', 'ambyarrr']
['seandainya', 'pasangan', 'capres', 'semangat', 'pasangan', 'anis', 'pasangan', 'prabowo', 'pasangan', 'gan', 'jar', 'pasangan', 'erlangga', 'rakyat', 'senang', 'disungguhkan', 'pilihan']
['golput', 'presidenya', 'menegakan', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'mentri', 'negeri', 'anies', 'mentri', 'negeri']
['orang', 'semangat']
['benar', 'ya', 'ayo', 'dukung']
['hubungannya', 'kursi', 'pilpres']
['kursi', 'y

In [197]:
stopword=[]
for i in range(len(tokenize)):
  listStopword =  set(stopwords.words('indonesian'))
  removed=[]
  for x in (tokenize[i]):
    if x not in listStopword:
       removed.append(x)
  stopword.append(removed)
  print(removed)

['prabowo', 'presiden', 'mudah', 'han', 'urusan', 'papua', 'langsung', 'selesai']
['anies', 'baswedan', 'is', 'the', 'best']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'menang']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'dukung', 'amp', 'menang']
['prabowo', 'tersandra', 'koalisinya', 'pkb', 'deklarasi', 'otomatis', 'cawapresnya', 'sih', 'imin', 'peminatnya', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikutan', 'nyungsep', 'ambyarrr']
['seandainya', 'pasangan', 'capres', 'semangat', 'pasangan', 'anis', 'pasangan', 'prabowo', 'pasangan', 'gan', 'jar', 'pasangan', 'erlangga', 'rakyat', 'senang', 'disungguhkan', 'pilihan']
['golput', 'presidenya', 'menegakan', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'mentri', 'negeri', 'anies', 'mentri', 'negeri']
['orang', 'semangat']
['ya', 'ayo', 'dukung']
['hubungannya', 'kursi', 'pilpres']
['kursi', 'ya', 'duduk']
['prabowo', 'subianto', 'djojohadiku

In [198]:
stemming=[]
for i in range(len(stopword)):
  factory = StemmerFactory()
  stemmer = factory.create_stemmer()
  katastem=[]
  for x in (stopword[i]):
    katastem.append(stemmer.stem(x))
  stemming.append(katastem)
  print(katastem)

['prabowo', 'presiden', 'mudah', 'han', 'urus', 'papua', 'langsung', 'selesai']
['anies', 'baswedan', 'is', 'the', 'best']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'menang']
['the', 'best', 'of', 'the', 'best', 'prabowo', 'presiden', 'ri', 'dukung', 'amp', 'menang']
['prabowo', 'tersandra', 'koalisi', 'pkb', 'deklarasi', 'otomatis', 'cawapresnya', 'sih', 'imin', 'minat', 'elektabilitas', 'imin', 'koma', 'elektabilitas', 'prabowo', 'ikut', 'nyungsep', 'ambyarrr']
['anda', 'pasang', 'capres', 'semangat', 'pasang', 'anis', 'pasang', 'prabowo', 'pasang', 'gan', 'jar', 'pasang', 'erlangga', 'rakyat', 'senang', 'sungguh', 'pilih']
['golput', 'presidenya', 'tega', 'sila', 'keadilab', 'rakyat', 'indonesia']
['prabowo', 'presiden', 'ganjar', 'tri', 'negeri', 'anies', 'tri', 'negeri']
['orang', 'semangat']
['ya', 'ayo', 'dukung']
['hubung', 'kursi', 'pilpres']
['kursi', 'ya', 'duduk']
['prabowo', 'subianto', 'djojohadikusumo']
[]
['golkar', 'nyalonin', 'presiden', 'takut

In [199]:
join=[]
for i in range(len(stemming)):
  joinkata = ' '.join(stemming[i])
  join.append(joinkata)

hasilpreproses = pd.DataFrame(join, columns=['data'])
hasilpreproses

data
0   prabowo presiden mudah han urus papua langsung...
1                          anies baswedan is the best
2     the best of the best prabowo presiden ri menang
3   the best of the best prabowo presiden ri dukun...
4   prabowo tersandra koalisi pkb deklarasi otomat...
5   anda pasang capres semangat pasang anis pasang...
6   golput presidenya tega sila keadilab rakyat in...
7   prabowo presiden ganjar tri negeri anies tri n...
8                                      orang semangat
9                                       ya ayo dukung
10                               hubung kursi pilpres
11                                     kursi ya duduk
12                   prabowo subianto djojohadikusumo
13                                                   
14  golkar nyalonin presiden takut kalah cari aman...
15                        waspada muncul soehartoisme
16  senang cinta mbak puan bangga pakai prabowo pr...
17                                                ayo
18  dukung gp afiliasi kaum biadab tengger jargon ...
19  iwan pahlawan noor mbak ketapang sampit hadir ...
20  p nyungsep kursi dpr ri zonk akar rumput pilih...
21                                     amin ya robbal
22        muncul ridwan kamil erick tohir biar partai
23  gerindra pkb gas pool capres n cawapres gabung...

TF IDF

In [200]:
tr_model  = TfidfVectorizer()
tf_vector = tr_model.fit_transform(hasilpreproses['data'])

In [201]:
tf_array = tf_vector.toarray()
print(tf_array)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.50900719 0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [202]:
words_set = tr_model.get_feature_names_out()
print(words_set)

['afiliasi' 'agama' 'akan' 'akar' 'akibat' 'aksi' 'alat' 'allohuakbar'
 'aman' 'ambisi' 'ambyarrr' 'amin' 'amp' 'anda' 'aneh' 'anies' 'anis'
 'apa' 'arb' 'ayat' 'ayo' 'badan' 'baik' 'baju' 'balut' 'bangga' 'bangsa'
 'baswedan' 'best' 'biadab' 'biar' 'bismillah' 'buai' 'bukti' 'busuk'
 'capres' 'cari' 'cawapres' 'cawapresnya' 'cinta' 'comot' 'dailih' 'dalih'
 'dalil' 'dampak' 'dandan' 'dekat' 'deklarasi' 'delusi' 'demokrasi'
 'derajat' 'didholimi' 'didik' 'djojohadikusumo' 'dki' 'dll' 'dosa' 'dpr'
 'duduk' 'dukung' 'dungu' 'durjana' 'egois' 'elektabilitas' 'erick'
 'erlangga' 'faham' 'fakta' 'fatamorgana' 'gabung' 'gan' 'ganggu' 'ganjar'
 'gas' 'gerindra' 'golkar' 'golput' 'gp' 'hadir' 'halal' 'halusinasi'
 'han' 'hasil' 'hubung' 'iblis' 'identitas' 'idiologi' 'ikut' 'imajinasi'
 'iman' 'imin' 'indonesia' 'is' 'iwan' 'jadi' 'jamin' 'jar' 'jargon'
 'juang' 'kader' 'kalah' 'kamil' 'kaum' 'keadilab' 'keagamisan' 'keburu'
 'kejumawaan' 'kes' 'ketapang' 'keummatan' 'koalisi' 'koma' 'koyak'
 

In [203]:
df = pd.DataFrame(tf_array, columns = words_set)
df

afiliasi     agama      akan      akar    akibat      aksi      alat  \
0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.042983  0.171932  0.042983  0.000000  0.042983  0.085966  0.085966   
19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
20  0.000000  0.000000  0.000000  0.378602  0.000000  0.000000  0.000000   
21  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
22  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
23  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

    allohuakbar      aman    ambisi  ...     tutup      ubah      ulah  \
0      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
1      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
2      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
3      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
4      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
5      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
6      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
7      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
8      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
9      0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
10     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
11     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
12     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
13     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
14     0.000000  0.358129  0.000000  ...  0.000000  0.000000  0.000000   
15     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
16     0.279183  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
17     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
18     0.000000  0.000000  0.085966  ...  0.042983  0.042983  0.042983   
19     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
20     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
21     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
22     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   
23     0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000   

       urus      usak     usung     waras   waspada        ya      zonk  
0   0.39283  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
1   0.00000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  
2   0.00000  0.000000  0.00000

Singular Value Decomposition


teknik untuk mendekomposisi matriks berukuran apa saja (biasanya diaplikasikan untuk matriks dengan ukuran sangat besar), untuk mempermudah pengolahan data

In [204]:
from sklearn.decomposition import TruncatedSVD
lsa_model = TruncatedSVD(n_components=3, algorithm='randomized', n_iter=10, random_state=42)
lsa_top=lsa_model.fit_transform(df)

In [205]:
print(lsa_top)
print(lsa_top.shape)  # (no_of_doc*no_of_topics)

[[ 1.63395092e-01 -5.19606675e-02 -2.63338079e-02]
 [ 6.44854098e-01 -1.91663207e-01  1.72029627e-02]
 [ 8.72713176e-01 -3.15991645e-01  6.65861274e-02]
 [ 8.80882471e-01 -2.51056919e-01  9.87889662e-02]
 [ 9.72305528e-02 -2.86517527e-02 -4.93368086e-02]
 [ 4.90015679e-02 -1.44348637e-02 -1.46083887e-02]
 [ 1.78888679e-03 -8.03248308e-04 -1.99314268e-04]
 [ 1.94229988e-01 -3.98581607e-02 -6.03890165e-02]
 [ 3.48518494e-03 -1.55485620e-03 -3.18457811e-03]
 [ 2.68540490e-01  7.96622197e-01  3.95493313e-01]
 [ 4.13894802e-02  1.59723561e-01 -4.66145488e-01]
 [ 1.42763051e-01  4.99041049e-01 -4.82905580e-01]
 [ 1.24761825e-01 -5.69530144e-02 -1.08604966e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.31350296e-02 -1.59048675e-02 -2.47473544e-02]
 [ 7.66937245e-04 -2.53892184e-04 -2.91800431e-03]
 [ 1.41307865e-01 -1.49356066e-02 -6.20248336e-02]
 [ 1.26367729e-01  5.65903198e-01  6.44972867e-01]
 [ 1.63586379e-02  1.53696224e-02  1.42832081e-02]
 [ 3.93640489e-01  3.95390276e-

In [206]:
#bobot setiap topik terhadap dokumen
dt = pd.DataFrame(lsa_top, columns=['topik1','topik2','topik3'])
dt

topik1    topik2    topik3
0   0.163395 -0.051961 -0.026334
1   0.644854 -0.191663  0.017203
2   0.872713 -0.315992  0.066586
3   0.880882 -0.251057  0.098789
4   0.097231 -0.028652 -0.049337
5   0.049002 -0.014435 -0.014608
6   0.001789 -0.000803 -0.000199
7   0.194230 -0.039858 -0.060389
8   0.003485 -0.001555 -0.003185
9   0.268540  0.796622  0.395493
10  0.041389  0.159724 -0.466145
11  0.142763  0.499041 -0.482906
12  0.124762 -0.056953 -0.010860
13  0.000000  0.000000  0.000000
14  0.083135 -0.015905 -0.024747
15  0.000767 -0.000254 -0.002918
16  0.141308 -0.014936 -0.062025
17  0.126368  0.565903  0.644973
18  0.016359  0.015370  0.014283
19  0.393640  0.395390 -0.282692
20  0.131079  0.095070 -0.399468
21  0.199182  0.558944 -0.326850
22  0.005767 -0.001249 -0.005597
23  0.073929  0.105705  0.088968

In [207]:
V = lsa_model.components_
print(V)
print(V.shape) # (no_of_topics*no_of_words)

[[ 2.93133304e-04  1.17253322e-03  2.93133304e-04  2.06801780e-02
   2.93133304e-04  5.86266609e-04  5.86266609e-04  1.64374114e-02
   1.24053278e-02  5.86266609e-04  8.91405487e-03  9.29248688e-02
   1.19408359e-01  3.46818118e-03  5.86266609e-04  1.70650093e-01
   1.76164138e-02  2.93133304e-04  2.93133304e-04  2.93133304e-04
   1.26367729e-01  2.93133304e-04  2.93133304e-04  2.93133304e-04
   5.86266609e-04  1.64374114e-02  1.75879983e-03  1.65708894e-01
   5.10706391e-01  1.46566652e-03  9.46762662e-04  1.64374114e-02
   2.93133304e-04  2.93133304e-04  2.93133304e-04  1.17852745e-02
   1.24053278e-02  1.03216104e-02  8.91405487e-03  1.64374114e-02
   5.86266609e-04  2.93133304e-04  5.86266609e-04  8.79399913e-04
   2.93133304e-04  2.93133304e-04  2.93133304e-04  8.91405487e-03
   8.79399913e-04  5.86266609e-04  2.93133304e-04  2.93133304e-04
   2.93133304e-04  3.40600062e-02  2.93133304e-04  2.93133304e-04
   2.93133304e-04  2.06801780e-02  4.01672944e-02  1.79832760e-01
   2.93133

In [208]:
a = V.shape[1]
print(a)

229


In [209]:
#bobot setiap kata terhadap topik
label=[]
for i in range (1,a+1):
  masukan = f"kata ke-{i}"
  label.append(masukan)
tabel = pd.DataFrame(V,columns=label)
tabel.rename(index={0:"topik1",1:"topik2",2:"topik3"})

kata ke-1  kata ke-2  kata ke-3  kata ke-4  kata ke-5  kata ke-6  \
topik1   0.000293   0.001173   0.000293   0.020680   0.000293   0.000586   
topik2   0.000342   0.001367   0.000342   0.018647   0.000342   0.000684   
topik3   0.000448   0.001792   0.000448  -0.108605   0.000448   0.000896   

        kata ke-7  kata ke-8  kata ke-9  kata ke-10  ...  kata ke-220  \
topik1   0.000586   0.016437   0.012405    0.000586  ...     0.000293   
topik2   0.000684  -0.002152  -0.002947    0.000684  ...     0.000342   
topik3   0.000896  -0.011932  -0.006407    0.000896  ...     0.000448   

        kata ke-221  kata ke-222  kata ke-223  kata ke-224  kata ke-225  \
topik1     0.000293     0.000293     0.026746     0.000293     0.000293   
topik2     0.000342     0.000342    -0.010585     0.000342     0.000342   
topik3     0.000448     0.000448    -0.007044     0.000448     0.000448   

        kata ke-226  kata ke-227  kata ke-228  kata ke-229  
topik1     0.000879     0.000193     0.169084     0.020680  
topik2     0.001025    -0.000080     0.549102     0.018647  
topik3     0.001344    -0.001329    -0.178503    -0.108605  

[3 rows x 229 columns]